name: paiqi_app
description: 看剧排期管理App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  table_calendar: ^3.0.9
  intl: ^0.20.2
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.13.0
  flutter_slidable: ^3.0.1
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
